name: ${name}
version: ${version}
description: ${description}
main: ru.epserv.deltabrix.paperutils.PaperUtils
api-version: '1.20'

commands:
  nickname:
    description: test
  skin:
    description: test
  profilereset:
    description: test